jaffleshop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      database: CLOUD_DBT_DEV_DB
      schema: CLOUD_DBT_DEV_SC
      threads: 8
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      database: CLOUD_DBT_PROD_DB
      schema: CLOUD_DBT_PROD_SC
      threads: 8
      client_session_keep_alive: False
    source:
      type: postgres
      host: localhost
      user: '{{ env_var("POSTGRES_USER") }}'
      password: '{{ env_var("POSTGRES_PASSWORD") }}'
      dbname: postgres
      schema: public
      threads: 4
      port: 5432